<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Services | Lab Admin</title>
<style>
body{margin:0;background:#f1f7fb;color:#12304c;font-family:Arial}.wrap{max-width:1120px;margin:42px auto;padding:0 20px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:22px}.back{color:#2476c7;text-decoration:none;font-weight:bold}.tabs{display:flex;gap:10px;margin-bottom:20px}.tabs a{padding:11px 17px;border-radius:8px;background:#e3eef5;color:#2476c7;text-decoration:none;font-weight:bold;font-size:14px}.tabs a:first-child{background:#13b9a6;color:#fff}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:20px;align-items:start}.card{background:#fff;border:1px solid #dce9f0;border-radius:14px;padding:24px;box-shadow:0 8px 22px #dce8ef;margin-bottom:20px}.card h2{margin:0 0 17px;font-size:20px}.card h3{font-size:17px;margin:0 0 6px}.section-note{color:#668099;font-size:13px;line-height:1.5;margin:0 0 16px}.field{margin:15px 0}.field label{display:block;margin-bottom:6px;font-size:13px;font-weight:bold}.hint{display:block;margin-top:5px;color:#71869a;font-size:11px}input,textarea,select{width:100%;padding:11px;box-sizing:border-box;border:1px solid #cbdce7;border-radius:8px;font:inherit;background:#fff}textarea{min-height:88px;resize:vertical}button{border:0;border-radius:8px;padding:12px 18px;background:#16b9a7;color:#fff;font-weight:bold;cursor:pointer}.success{margin-bottom:18px;padding:12px;border-radius:8px;background:#def9f2;color:#087a6b}.service{padding:15px 0;border-bottom:1px solid #e1ecf2}.service:last-child{border:0}.service h3{margin:0 0 6px;font-size:16px}.service p{margin:0;color:#668099;font-size:13px;line-height:1.5}.badge{display:inline-block;margin-top:8px;padding:4px 7px;border-radius:12px;background:#e2faf4;color:#078a78;font-size:11px;font-weight:bold}.edit-service{display:inline-block;margin:8px 0 0 10px;color:#2476c7;font-size:12px;font-weight:bold;text-decoration:none}.delete-service-form{display:inline-block;margin-left:8px}.delete-service{padding:5px 10px;border-radius:6px;background:#dc4b52;font-size:12px}.delete-service:hover{background:#bd3038}.mini-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mini-card{padding:13px;border:1px solid #e0ebf1;border-radius:10px}.mini-card .field{margin:0 0 10px}.mini-card .field:last-child{margin-bottom:0}.mini-card textarea{min-height:72px}@media(max-width:700px){.grid,.mini-grid{grid-template-columns:1fr}.top{align-items:flex-start;gap:10px;flex-direction:column}}
</style></head>
<body class="admin-inner-page">
@include('components.admin-sidebar')
<main class="wrap">
<header class="top"><div><h1>Services</h1><p>Manage all laboratory services from one place.</p></div><a class="back" href="{{ route('admin.dashboard') }}">← Dashboard</a></header>
<nav class="tabs"><a href="#add">+ Add Service</a><a href="#view">View Services ({{ $services->count() }})</a></nav>
@if(session('success'))<div class="success">{{ session('success') }}</div>@endif
<div class="grid"><div>
<section class="card" id="add"><h2>Add Service</h2><form method="post" action="{{ route('admin.services.store') }}" enctype="multipart/form-data">@csrf
<div class="field"><label>Service name</label><input name="name" required placeholder="e.g. Chemistry Testing"></div>
<div class="field"><label>Short description</label><textarea name="summary" placeholder="Brief description of this service"></textarea></div>
<hr style="border:0;border-top:1px solid #e1ecf2;margin:22px 0"><h3>Search Engine Optimization</h3>
<div class="field"><label>Meta title</label><input name="meta_title" maxlength="255" placeholder="SEO title shown in search results"><span class="hint">Recommended length: 50–60 characters.</span></div>
<div class="field"><label>Meta description</label><textarea name="meta_description" maxlength="500" placeholder="Short search result description"></textarea><span class="hint">Recommended length: 150–160 characters.</span></div>
<div class="field"><label>Meta keywords</label><input name="meta_keywords" maxlength="500" placeholder="laboratory testing, diagnostics, chemistry"><span class="hint">Separate keywords with commas.</span></div>
<hr style="border:0;border-top:1px solid #e1ecf2;margin:22px 0"><h3>Hero section content</h3>
<div class="field"><label>Hero heading</label><input name="hero_heading" placeholder="e.g. Chemistry Testing"><span class="hint">Heading displayed on the service page banner.</span></div>
<div class="field"><label>Hero description</label><textarea name="hero_description" placeholder="Description displayed below the hero heading"></textarea></div>
<div class="field"><label>Hero image</label><input type="file" name="hero_image" accept="image/png,image/jpeg,image/webp"><span class="hint">JPG, PNG or WebP. Maximum size: 5 MB.</span></div>
<div class="field"><label>Hero button text</label><input name="button_text" value="Book an Appointment"></div>
<div class="field"><label>Hero button link</label><input name="button_link" value="/appointment"></div>
<hr style="border:0;border-top:1px solid #e1ecf2;margin:22px 0"><h3>FAQ section content</h3>
<div class="field"><label>FAQ heading</label><input name="faq_heading" placeholder="e.g. Chemistry Testing FAQs"></div>
<div class="field"><label>FAQ description</label><textarea name="faq_description" placeholder="Answers to common questions about this service"></textarea></div>
<button>Add service</button></form></section>
<section class="card"><h2>Molecular Cards Section</h2><p class="section-note">This section is displayed on the Chemistry Testing service page. Changes saved here appear there directly.</p><form method="post" action="{{ route('admin.molecular-specimens.update') }}">@csrf
<div class="field"><label>Section heading</label><input name="heading" value="{{ old('heading', $molecular['heading']) }}" required></div>
<div class="field"><label>Section description</label><textarea name="description" required>{{ old('description', $molecular['description']) }}</textarea></div>
<div class="mini-grid">@for($i=0;$i<4;$i++)<div class="mini-card"><div class="field"><label>Card {{ $i + 1 }} heading</label><input name="card_heading[]" value="{{ old('card_heading.'.$i, $molecular['card_heading'][$i]) }}" required></div><div class="field"><label>Card {{ $i + 1 }} description</label><textarea name="card_description[]" required>{{ old('card_description.'.$i, $molecular['card_description'][$i]) }}</textarea></div></div>@endfor</div><br><button>Save cards section</button></form></section>
</div>
<section class="card" id="view"><h2>All Services</h2>@forelse($services as $service)<article class="service"><h3>{{ $service->name }}</h3><p>{{ $service->summary ?: 'No description added yet.' }}</p><span class="badge">{{ $service->is_active ? 'Active' : 'Inactive' }}</span><a class="edit-service" href="{{ route('admin.services.edit', $service->id) }}">Edit service</a><form class="delete-service-form" method="post" action="{{ route('admin.services.delete', $service->id) }}" onsubmit="return confirm('Delete this service? Its assigned tests and service FAQs will also be deleted.');">@csrf<button class="delete-service" type="submit">Delete</button></form></article>@empty<p>No services added yet. Use the form to add your first service.</p>@endforelse</section>
<section class="card"><h2>Change Service Hero Image</h2><p class="section-note">Choose an existing service and upload a new banner image.</p><form method="post" action="{{ route('admin.services.hero-image.update') }}" enctype="multipart/form-data">@csrf<div class="field"><label>Service</label><select name="service_id" required>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select></div><div class="field"><label>Hero image</label><input type="file" name="hero_image" accept="image/png,image/jpeg,image/webp" required><span class="hint">JPG, PNG or WebP. Maximum size: 5 MB.</span></div><button>Save hero image</button></form></section>
</div></main></body></html>
