<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Home Hero | Lab Admin</title>
    <style>
        :root{--navy:#082942;--teal:#18bca9;--ink:#12314e;--muted:#6f879c;--line:#dce8f0}*{box-sizing:border-box}body{margin:0;background:#f2f7fa;color:var(--ink);font-family:Inter,Arial,sans-serif}.page{max-width:1120px;margin:0 auto;padding:34px 20px 60px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:26px}.back{color:#2775ca;text-decoration:none;font-weight:700;font-size:14px}.title h1{margin:0 0 6px;font-size:28px}.title p{margin:0;color:var(--muted)}.card{display:grid;grid-template-columns:1.2fr .8fr;gap:28px;padding:30px;background:#fff;border:1px solid var(--line);border-radius:18px;box-shadow:0 12px 32px rgba(24,61,88,.08)}.form-title{margin:0 0 20px;font-size:18px}.field{margin-bottom:17px}.field label{display:block;margin-bottom:7px;font-size:13px;font-weight:750}.field small{display:block;margin-top:5px;color:var(--muted);font-size:11px}input,textarea{width:100%;padding:12px 13px;border:1px solid #cadbe6;border-radius:9px;color:var(--ink);font:inherit;font-size:14px;outline:none}textarea{min-height:108px;resize:vertical}input:focus,textarea:focus{border-color:var(--teal);box-shadow:0 0 0 3px rgba(24,188,169,.12)}.button-row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.save{margin-top:8px;width:100%;border:0;border-radius:9px;padding:14px;background:linear-gradient(90deg,#069b8a,#1dbbaf);color:#fff;font-weight:800;font-size:14px;cursor:pointer}.preview{padding:20px;border-radius:14px;background:linear-gradient(135deg,#093b62,#0d887f);color:#fff;min-height:400px}.preview h2{margin:0 0 10px;font-size:25px;line-height:1.15}.preview p{color:#d0eef0;line-height:1.6;font-size:14px}.preview img{width:100%;height:170px;object-fit:cover;margin:15px 0;border-radius:10px;background:#d9e9ef}.preview-actions{display:flex;gap:9px;margin-top:20px}.preview-actions span{padding:10px 13px;border-radius:99px;background:#1fc1b8;font-size:12px;font-weight:700}.preview-actions span+span{background:transparent;border:1px solid rgba(255,255,255,.6)}.alert{padding:12px 14px;margin-bottom:18px;border-radius:9px;background:#e4faf5;color:#087b6d;font-size:13px;font-weight:700}.errors{padding:12px 14px;margin-bottom:18px;border-radius:9px;background:#fff1f1;color:#a32929;font-size:13px}@media(max-width:760px){.top{align-items:flex-start;gap:14px;flex-direction:column}.card{grid-template-columns:1fr;padding:20px}.preview{min-height:auto}.button-row{grid-template-columns:1fr}}
    </style>
</head>
<body>
    <main class="page">
        <header class="top"><div class="title"><h1>Home page hero</h1><p>Edit the image, content, and both call-to-action buttons shown at the top of your home page.</p></div><a class="back" href="{{ route('admin.dashboard') }}">← Back to dashboard</a></header>
        <nav style="display:flex;gap:8px;margin-bottom:18px">@for($i=1;$i<=3;$i++)<a href="{{ route('admin.home-hero.edit',['slide'=>$i]) }}" style="padding:9px 18px;border-radius:8px;text-decoration:none;font-size:13px;font-weight:700;color:{{ $slide===$i?'#fff':'#2775ca' }};background:{{ $slide===$i?'#16b9a7':'#e5f0f7' }}">Hero option {{ $i }}</a>@endfor</nav>
        @if(session('success'))<div class="alert">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="errors">Please correct the highlighted fields and save again.</div>@endif
        <form class="card" method="POST" action="{{ route('admin.home-hero.update') }}" enctype="multipart/form-data">@csrf<input type="hidden" name="slide" value="{{ $slide }}">
            <section><h2 class="form-title">Hero content</h2><div class="field"><label for="heading">Heading</label><textarea id="heading" name="heading" required>{{ old('heading',$hero->heading) }}</textarea><small>Use a new line where you want a heading break.</small></div><div class="field"><label for="description">Description</label><textarea id="description" name="description">{{ old('description',$hero->description) }}</textarea></div><div class="field"><label for="image">Hero image</label><input id="image" type="file" name="image" accept="image/png,image/jpeg,image/webp"><small>JPG, PNG or WebP. Maximum file size: 5 MB.</small></div><div class="button-row"><div class="field"><label for="primary_button_text">Primary button text</label><input id="primary_button_text" name="primary_button_text" value="{{ old('primary_button_text',$hero->primary_button_text) }}" required></div><div class="field"><label for="primary_button_link">Primary button link</label><input id="primary_button_link" name="primary_button_link" value="{{ old('primary_button_link',$hero->primary_button_link) }}" required></div><div class="field"><label for="secondary_button_text">Second button text</label><input id="secondary_button_text" name="secondary_button_text" value="{{ old('secondary_button_text',$hero->secondary_button_text) }}" required></div><div class="field"><label for="secondary_button_link">Second button link</label><input id="secondary_button_link" name="secondary_button_link" value="{{ old('secondary_button_link',$hero->secondary_button_link) }}" required></div></div><button class="save" type="submit">Save hero changes</button></section>
            <aside class="preview"><div class="eyebrow">Live content preview</div><h2 id="preview-heading">{{ $hero->heading }}</h2><p id="preview-description">{{ $hero->description }}</p><img id="preview-image" src="{{ !empty($hero->image_path) ? asset('storage/'.$hero->image_path) : asset('img/hero-doc-img.png') }}" alt="Hero preview"><div class="preview-actions"><span id="preview-primary">{{ $hero->primary_button_text }}</span><span id="preview-secondary">{{ $hero->secondary_button_text }}</span></div></aside>
        </form>
    </main>
    <script>const link=(input,target)=>input.addEventListener('input',()=>target.textContent=input.value);link(document.querySelector('#heading'),document.querySelector('#preview-heading'));link(document.querySelector('#description'),document.querySelector('#preview-description'));link(document.querySelector('#primary_button_text'),document.querySelector('#preview-primary'));link(document.querySelector('#secondary_button_text'),document.querySelector('#preview-secondary'));document.querySelector('#image').addEventListener('change',e=>{if(e.target.files[0])document.querySelector('#preview-image').src=URL.createObjectURL(e.target.files[0])});</script>
</body>
</html>
