<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use Illuminate\Support\Facades\DB;

DB::statement('SET FOREIGN_KEY_CHECKS=0;');
DB::table('test_page_results')->truncate();
DB::table('test_page_components')->truncate();
DB::table('test_pages')->truncate();
DB::table('service_faqs')->truncate();
DB::table('tests')->truncate();
DB::statement('SET FOREIGN_KEY_CHECKS=1;');

$pages = array (
  0 => 
  (object) array(
     'id' => 1,
     'service_id' => 1,
     'title' => 'Comprehensive Metabolic Panel',
     'slug' => 'comprehensive-metabolic-panel',
     'description' => 'A Comprehensive Metabolic Panel (CMP) is a blood test that measures 14 different substances in your blood. It provides crucial information about your body\'s chemical balance and metabolism, offering a broad view of your overall health, kidney, and liver function.',
     'bg_image' => 'test_pages/comprehensive-metabolic-panel-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum',
     'quick_info_prep' => 'Fast for 10-12 hours prior to testing',
     'about_heading' => 'What is a Comprehensive Metabolic Panel (CMP)?',
     'about_text' => 'The Comprehensive Metabolic Panel (CMP) is a blood test that measures 14 different substances in your blood. It provides important information about your body\'s chemical balance and metabolism. This includes checking your kidney and liver function, blood sugar levels, and electrolyte and fluid balance.',
     'about_image' => 'test_pages/comprehensive-metabolic-panel-about.jpg',
     'status' => 'active',
     'faq_heading' => 'Frequently Asked Questions about CMP',
     'faq_description' => 'Common questions regarding the Comprehensive Metabolic Panel.',
     'created_at' => '2026-09-15 12:08:50',
     'updated_at' => '2026-09-16 12:35:39',
     'components_heading' => 'What Does a CMP Measure?',
     'components_text' => 'The CMP measures 14 specific components to give a broad picture of your health.',
     'specimen_title' => 'What Sample is Needed?',
     'specimen_description' => 'A blood sample is required for a CMP.',
     'specimen_items' => 'Blood drawn from a vein in your arm.
Usually performed in a clinic or laboratory.',
     'preparation_title' => 'How Should You Prepare?',
     'preparation_description' => 'Fasting is typically required before a CMP.',
     'preparation_items' => 'Do not eat or drink anything (except water) for 10-12 hours before the test.
Continue taking your regular medications unless instructed otherwise by your doctor.',
     'results_heading' => 'Understanding Your CMP Results',
     'results_text' => 'Your results will show the levels of each of the 14 substances. Your doctor will interpret these in the context of your overall health. A CMP provides a broad look at how well your kidneys and liver are functioning, checks your blood sugar levels, and evaluates your electrolyte and fluid balance. Minor fluctuations are common, but significant abnormalities can help diagnose diabetes, kidney disease, liver damage, and other metabolic conditions.',
  ),
  1 => 
  (object) array(
     'id' => 2,
     'service_id' => 1,
     'title' => 'Basic Metabolic Panel',
     'slug' => 'basic-metabolic-panel',
     'description' => 'A Basic Metabolic Panel (BMP) is a standard blood test that measures eight specific substances in your blood to evaluate your body\'s metabolism. This test helps assess kidney function, blood sugar levels, and electrolyte and acid/base balance.',
     'bg_image' => 'test_pages/basic-metabolic-panel-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum or Plasma',
     'quick_info_prep' => 'Usually fast for 10-12 hours prior to testing',
     'about_heading' => 'What is a Basic Metabolic Panel (BMP)?',
     'about_text' => 'The Basic Metabolic Panel (BMP) is a frequently ordered blood test that provides important information about your metabolism. It measures 8 key substances in your blood to evaluate your kidney function, blood sugar levels, and electrolyte balance. It is an essential tool for monitoring acute and chronic health conditions.',
     'about_image' => 'test_pages/basic-metabolic-panel-about.jpg',
     'status' => 'published',
     'faq_heading' => 'BMP Frequently Asked Questions',
     'faq_description' => 'Learn more about the Basic Metabolic Panel.',
     'created_at' => '2026-09-15 13:49:05',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does a BMP Measure?',
     'components_text' => 'The BMP includes 8 distinct measurements.',
     'specimen_title' => 'What Sample is Needed?',
     'specimen_description' => 'A standard blood draw is required.',
     'specimen_items' => 'Venous blood sample.
Collected by a phlebotomist.',
     'preparation_title' => 'How Should You Prepare?',
     'preparation_description' => 'Your doctor will tell you if you need to fast.',
     'preparation_items' => 'Fasting (no food or drink except water) for 8 to 12 hours may be required.
If ordered without fasting, you can eat and drink normally.',
     'results_heading' => 'Understanding Your BMP Results',
     'results_text' => 'BMP results help diagnose a wide range of conditions, from dehydration to kidney failure. By measuring your blood sugar, kidney function, and electrolyte levels, this panel gives your healthcare provider a clear snapshot of your metabolism and chemical balance. Abnormal results can point to acute issues that need immediate medical attention or help track the progression of chronic diseases over time.',
  ),
  2 => 
  (object) array(
     'id' => 3,
     'service_id' => 1,
     'title' => 'Lipid Panel',
     'slug' => 'lipid-panel',
     'description' => 'A Lipid Panel is a crucial blood test used to monitor and screen for cardiovascular disease risks. It measures the amount of cholesterol and triglycerides in your blood, helping doctors determine your risk of plaque buildup in your arteries.',
     'bg_image' => 'test_pages/lipid-panel-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum',
     'quick_info_prep' => 'Fast for 9-12 hours prior to testing',
     'about_heading' => 'What is a Lipid Panel?',
     'about_text' => 'A lipid panel is a blood test that measures the amount of certain fat molecules called lipids in your blood. In most cases, the panel includes four different cholesterol measurements and a measurement of your triglycerides. Having too many lipids in your blood can lead to buildup in your blood vessels and arteries, which can cause cardiovascular diseases.',
     'about_image' => 'test_pages/lipid-panel-about.jpg',
     'status' => 'published',
     'faq_heading' => 'Lipid Panel FAQs',
     'faq_description' => 'Common questions about cholesterol testing.',
     'created_at' => '2026-09-15 13:49:39',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does a Lipid Panel Measure?',
     'components_text' => 'The lipid panel typically measures five key components.',
     'specimen_title' => 'Sample Requirements',
     'specimen_description' => 'A standard venous blood sample.',
     'specimen_items' => 'Drawn from a vein in the arm.
Quick and relatively painless.',
     'preparation_title' => 'Test Preparation',
     'preparation_description' => 'Fasting is traditionally required, though non-fasting lipid panels are becoming more common.',
     'preparation_items' => 'Usually requires fasting for 9 to 12 hours before the blood draw.
Water is permitted.
Consult your physician on whether fasting is required for your specific case.',
     'results_heading' => 'What Do The Results Mean?',
     'results_text' => 'Your lipid panel results are used to calculate your risk of cardiovascular disease. This includes assessing your levels of \'good\' HDL cholesterol, \'bad\' LDL cholesterol, and triglycerides. By understanding your complete lipid profile, your doctor can determine your risk for heart attacks and strokes, and recommend targeted lifestyle changes, dietary adjustments, or cholesterol-lowering medications to keep your heart healthy.',
  ),
  3 => 
  (object) array(
     'id' => 4,
     'service_id' => 2,
     'title' => 'Troponin',
     'slug' => 'troponin',
     'description' => 'The Troponin test measures the levels of troponin proteins in the blood. These proteins are released when the heart muscle has been damaged, making this test a critical tool in diagnosing a heart attack and evaluating other types of heart injury.',
     'bg_image' => 'test_pages/troponin-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum or Plasma',
     'quick_info_prep' => 'No special preparation needed',
     'about_heading' => 'What is a Troponin Test?',
     'about_text' => 'A troponin test measures the levels of troponin T or troponin I proteins in the blood. These proteins are released when the heart muscle has been damaged, such as occurs with a heart attack. The more damage there is to the heart, the greater the amount of troponin T and I there will be in the blood.',
     'about_image' => 'test_pages/troponin-about.jpg',
     'status' => 'published',
     'faq_heading' => 'Troponin Test FAQs',
     'faq_description' => 'Questions about troponin testing.',
     'created_at' => '2026-09-15 13:56:54',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does it Measure?',
     'components_text' => 'The test specifically looks for cardiac-specific troponins.',
     'specimen_title' => 'Specimen Collection',
     'specimen_description' => 'A venous blood sample is required.',
     'specimen_items' => 'Blood drawn from a vein.
Often drawn in an emergency setting.
Serial testing (multiple draws over several hours) is standard practice.',
     'preparation_title' => 'Preparation',
     'preparation_description' => 'No special preparation is needed.',
     'preparation_items' => 'No fasting is required.
This test is often performed in emergency situations where preparation is not possible.',
     'results_heading' => 'Interpreting Troponin Levels',
     'results_text' => 'Even a slight increase in troponin levels can indicate some damage to the heart muscle. Because troponin is highly specific to cardiac tissue, elevated levels are a critical marker used by emergency room doctors to diagnose a heart attack (myocardial infarction). Serial testing over several hours helps track the pattern of troponin release, ensuring an accurate and timely diagnosis for optimal patient care and recovery.',
  ),
  4 => 
  (object) array(
     'id' => 5,
     'service_id' => 2,
     'title' => 'Thyroid Stimulating Hormone (TSH)',
     'slug' => 'thyroid-stimulating-hormone-tsh',
     'description' => 'The TSH (Thyroid Stimulating Hormone) test is a blood test used to check for thyroid gland problems. It measures how much TSH is in your blood, which helps determine if your thyroid is overactive (hyperthyroidism) or underactive (hypothyroidism).',
     'bg_image' => 'test_pages/thyroid-stimulating-hormone-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum',
     'quick_info_prep' => 'No special preparation needed',
     'about_heading' => 'What is a TSH Test?',
     'about_text' => 'A TSH (Thyroid Stimulating Hormone) test is a blood test that measures the amount of TSH in your blood. TSH is produced by the pituitary gland and tells the thyroid gland to make and release thyroid hormones into the blood. This test is the most sensitive marker for screening for thyroid diseases and conditions.',
     'about_image' => 'test_pages/thyroid_stimulating_hormone_about.jpg',
     'status' => 'published',
     'faq_heading' => 'TSH Test FAQs',
     'faq_description' => 'Common questions regarding the TSH test.',
     'created_at' => '2026-09-16 06:43:41',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does the TSH Test Measure?',
     'components_text' => 'It measures a single hormone to evaluate thyroid function.',
     'specimen_title' => 'Sample Required',
     'specimen_description' => 'A standard blood sample.',
     'specimen_items' => 'Blood sample from a vein.
Can be drawn at any time of the day.',
     'preparation_title' => 'Preparation Instructions',
     'preparation_description' => 'Generally, no special preparation is needed.',
     'preparation_items' => 'No fasting required.
Certain medications (like biotin) can interfere with the assay; tell your doctor about all supplements you take.',
     'results_heading' => 'Understanding TSH Results',
     'results_text' => 'TSH levels have an inverse relationship with thyroid hormone levels. When your thyroid gland is not producing enough hormones, your pituitary gland releases more TSH to stimulate it. Conversely, if your thyroid is overactive, TSH production drops. Your doctor will use these results to evaluate your thyroid health, monitor ongoing treatments, and determine if any adjustments to your medication or lifestyle are necessary.',
  ),
  5 => 
  (object) array(
     'id' => 6,
     'service_id' => 2,
     'title' => 'Free T4',
     'slug' => 'free-t4',
     'description' => 'A Free T4 test measures the level of free thyroxine (T4) in your blood. T4 is a hormone produced by the thyroid gland that plays a crucial role in regulating your body\'s metabolism, heart rate, and temperature.',
     'bg_image' => 'test_pages/free-t4-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Serum',
     'quick_info_prep' => 'No special preparation needed',
     'about_heading' => 'What is a Free T4 Test?',
     'about_text' => 'A Free T4 (thyroxine) test measures the level of free thyroxine in your blood. Thyroxine is the main hormone produced by the thyroid gland. Most T4 in the blood is bound to protein; the "free" T4 is the active form of the hormone that is available to enter tissues and exert its effects. This test is used alongside a TSH test to evaluate thyroid function.',
     'about_image' => 'test_pages/free_t4_about.jpg',
     'status' => 'published',
     'faq_heading' => 'Free T4 FAQs',
     'faq_description' => 'Questions about the Free T4 blood test.',
     'created_at' => '2026-09-16 06:43:41',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does Free T4 Measure?',
     'components_text' => 'It measures the active form of the thyroid hormone.',
     'specimen_title' => 'Sample Requirements',
     'specimen_description' => 'A blood sample is required.',
     'specimen_items' => 'Venous blood draw.
Collected in a standard laboratory tube.',
     'preparation_title' => 'Test Preparation',
     'preparation_description' => 'No special preparation is typically required.',
     'preparation_items' => 'No fasting is necessary.
Inform your doctor if you take thyroid replacement medication, as the timing of your dose may affect the results.',
     'results_heading' => 'Interpreting Free T4 Results',
     'results_text' => 'Free T4 results are almost always interpreted in conjunction with TSH results. By evaluating both hormones together, your healthcare provider can accurately diagnose whether you have an overactive thyroid (hyperthyroidism), an underactive thyroid (hypothyroidism), or if your thyroid function is completely normal. Keep in mind that certain medications and medical conditions can also temporarily affect these levels, so a comprehensive clinical evaluation is essential.',
  ),
  6 => 
  (object) array(
     'id' => 7,
     'service_id' => 3,
     'title' => 'Complete Blood Count (CBC)',
     'slug' => 'complete-blood-count-cbc',
     'description' => 'A Complete Blood Count (CBC) is a common blood test used to evaluate your overall health and detect a wide range of disorders, including anemia, infection and leukemia. It measures several components of your blood, including red blood cells, white blood cells, and platelets.',
     'bg_image' => 'test_pages/complete-blood-count-cbc-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Whole Blood',
     'quick_info_prep' => 'Usually no special preparation',
     'about_heading' => 'What is a Complete Blood Count (CBC)?',
     'about_text' => 'A Complete Blood Count (CBC) is one of the most common blood tests. It evaluates your overall health and can detect a wide range of disorders, including anemia, infection, and leukemia. The CBC measures several components and features of your blood, providing a comprehensive overview of your blood cells.',
     'about_image' => 'test_pages/complete_blood_count_cbc_about.jpg',
     'status' => 'published',
     'faq_heading' => 'CBC FAQs',
     'faq_description' => 'Common questions about the Complete Blood Count.',
     'created_at' => '2026-09-16 06:43:41',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does a CBC Measure?',
     'components_text' => 'A CBC measures the three main types of cells in your blood.',
     'specimen_title' => 'Specimen Collection',
     'specimen_description' => 'A standard blood sample.',
     'specimen_items' => 'Venous blood drawn from the arm.
Collected in a tube containing an anticoagulant (EDTA) to prevent clotting.',
     'preparation_title' => 'Preparation',
     'preparation_description' => 'Usually, no preparation is required.',
     'preparation_items' => 'No fasting is necessary if a CBC is the only test being performed.
If part of a larger panel, fasting may be required.',
     'results_heading' => 'Understanding CBC Results',
     'results_text' => 'Abnormal levels in a CBC can indicate various health issues. Since this test evaluates your red blood cells, white blood cells, and platelets, it provides a comprehensive overview of your overall health. Your doctor uses these results to screen for anemia, detect underlying infections, monitor ongoing medical treatments, and identify blood disorders or immune system deficiencies.',
  ),
  7 => 
  (object) array(
     'id' => 8,
     'service_id' => 3,
     'title' => 'CBC with Differential',
     'slug' => 'cbc-with-differential',
     'description' => 'A CBC with Differential measures the number of each type of white blood cell in your blood. It is used to help diagnose and monitor many different conditions, including infections, autoimmune diseases, and leukemia.',
     'bg_image' => 'test_pages/cbc-with-differential-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Whole Blood',
     'quick_info_prep' => 'Usually no special preparation',
     'about_heading' => 'What is a CBC with Differential?',
     'about_text' => 'A CBC with Differential includes all the measurements of a standard Complete Blood Count, but it also measures the number of each type of white blood cell. This detailed breakdown helps doctors pinpoint the specific cause of an abnormal white blood cell count, such as distinguishing between a bacterial infection, a viral infection, or an allergic reaction.',
     'about_image' => 'test_pages/cbc_with_differential_about.jpg',
     'status' => 'published',
     'faq_heading' => 'CBC with Differential FAQs',
     'faq_description' => 'Questions about the differential test.',
     'created_at' => '2026-09-16 06:43:41',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Does the Differential Measure?',
     'components_text' => 'It measures the five major types of white blood cells.',
     'specimen_title' => 'Sample Requirements',
     'specimen_description' => 'A standard blood sample.',
     'specimen_items' => 'Venous blood draw.
Collected in a lavender-top tube (EDTA).',
     'preparation_title' => 'Test Preparation',
     'preparation_description' => 'No special preparation is needed.',
     'preparation_items' => 'No fasting required.
Can be drawn at any time of day.',
     'results_heading' => 'Interpreting the Differential',
     'results_text' => 'The differential results show the percentage (and absolute number) of each white blood cell type. By breaking down your white blood cells into five specific categories, your healthcare provider can identify the exact nature of an immune response. This detailed information is crucial for distinguishing between bacterial infections, viral illnesses, allergic reactions, and more complex inflammatory or autoimmune conditions.',
  ),
  8 => 
  (object) array(
     'id' => 9,
     'service_id' => 3,
     'title' => 'Hemoglobin & Hematocrit',
     'slug' => 'hemoglobin-hematocrit',
     'description' => 'Hemoglobin and Hematocrit (H&H) tests are often performed together to check for anemia. Hemoglobin measures the oxygen-carrying protein in red blood cells, while hematocrit measures the proportion of red blood cells in your blood.',
     'bg_image' => 'test_pages/hemoglobin-hematocrit-hero.jpg',
     'quick_info_type' => 'Blood Test',
     'quick_info_specimen' => 'Whole Blood',
     'quick_info_prep' => 'No special preparation needed',
     'about_heading' => 'What are Hemoglobin and Hematocrit (H&H) Tests?',
     'about_text' => 'Hemoglobin and hematocrit are two closely related blood tests often performed together to evaluate red blood cells. Hemoglobin is the protein in red blood cells that carries oxygen. Hematocrit measures the percentage of your blood volume that is made up of red blood cells. These tests are the primary tools used to diagnose and monitor anemia.',
     'about_image' => 'test_pages/hemoglobin_hematocrit_about.jpg',
     'status' => 'published',
     'faq_heading' => 'H&H Test FAQs',
     'faq_description' => 'Common questions about Hemoglobin and Hematocrit testing.',
     'created_at' => '2026-09-16 06:43:41',
     'updated_at' => '2026-09-16 10:52:11',
     'components_heading' => 'What Do H&H Tests Measure?',
     'components_text' => 'These tests assess the oxygen-carrying capacity of your blood.',
     'specimen_title' => 'Sample Required',
     'specimen_description' => 'A small blood sample is needed.',
     'specimen_items' => 'Can be drawn from a vein.
Can also be performed via a finger prick (capillary sample).',
     'preparation_title' => 'Test Preparation',
     'preparation_description' => 'No special preparation is required.',
     'preparation_items' => 'No fasting is necessary.
Maintain normal hydration before the test.',
     'results_heading' => 'Understanding H&H Results',
     'results_text' => 'Hemoglobin and hematocrit levels generally rise and fall together. These two measurements are the gold standard for diagnosing anemia, a condition where your blood lacks enough healthy red blood cells to carry adequate oxygen to your body\'s tissues. Depending on whether your results are high or low, your healthcare provider can pinpoint underlying causes such as iron deficiency, chronic illness, blood loss, or dehydration, and recommend an appropriate treatment plan.',
  ),
);
foreach($pages as $p) { DB::table('test_pages')->insert((array)$p); }

$components = array (
  0 => 
  (object) array(
     'id' => 91,
     'test_page_id' => 1,
     'title' => 'Glucose',
     'description' => 'A type of sugar and your body\'s main source of energy.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  1 => 
  (object) array(
     'id' => 92,
     'test_page_id' => 1,
     'title' => 'Calcium',
     'description' => 'Essential for proper functioning of your muscles, nerves, and heart.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  2 => 
  (object) array(
     'id' => 93,
     'test_page_id' => 1,
     'title' => 'Electrolytes',
     'description' => 'These are electrolytes that help maintain fluid balance and acid-base balance.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  3 => 
  (object) array(
     'id' => 94,
     'test_page_id' => 1,
     'title' => 'Kidney Markers',
     'description' => 'Waste products filtered out of the blood by the kidneys. These indicate how well the kidneys are working.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  4 => 
  (object) array(
     'id' => 97,
     'test_page_id' => 2,
     'title' => 'Glucose',
     'description' => 'The primary energy source for the body\'s cells.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  5 => 
  (object) array(
     'id' => 98,
     'test_page_id' => 2,
     'title' => 'Calcium',
     'description' => 'Crucial for bone health, muscle contraction, and nerve signaling.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  6 => 
  (object) array(
     'id' => 99,
     'test_page_id' => 2,
     'title' => 'Electrolytes',
     'description' => 'Electrolytes critical for fluid balance and cellular function.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  7 => 
  (object) array(
     'id' => 100,
     'test_page_id' => 2,
     'title' => 'Bicarbonate',
     'description' => 'Helps maintain the body\'s pH (acid-base) balance.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  8 => 
  (object) array(
     'id' => 101,
     'test_page_id' => 2,
     'title' => 'Chloride',
     'description' => 'An electrolyte that works with sodium to maintain fluid balance.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  9 => 
  (object) array(
     'id' => 102,
     'test_page_id' => 2,
     'title' => 'BUN Level',
     'description' => 'A waste product from protein breakdown, used to check kidney function.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  10 => 
  (object) array(
     'id' => 103,
     'test_page_id' => 2,
     'title' => 'Creatinine',
     'description' => 'A waste product from muscle breakdown, an important indicator of kidney health.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  11 => 
  (object) array(
     'id' => 104,
     'test_page_id' => 3,
     'title' => 'Cholesterol',
     'description' => 'The overall amount of cholesterol in your blood.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  12 => 
  (object) array(
     'id' => 105,
     'test_page_id' => 3,
     'title' => 'LDL (Bad)',
     'description' => 'Known as "bad" cholesterol. High levels lead to plaque buildup in arteries.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  13 => 
  (object) array(
     'id' => 106,
     'test_page_id' => 3,
     'title' => 'HDL (Good)',
     'description' => 'Known as "good" cholesterol. It helps carry LDL cholesterol away from the arteries.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  14 => 
  (object) array(
     'id' => 107,
     'test_page_id' => 3,
     'title' => 'Triglycerides',
     'description' => 'A type of fat from the food you eat. Excess calories, alcohol, or sugar are converted into triglycerides and stored in fat cells.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  15 => 
  (object) array(
     'id' => 108,
     'test_page_id' => 3,
     'title' => 'VLDL Level',
     'description' => 'Usually calculated rather than directly measured. VLDL also contributes to plaque buildup.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  16 => 
  (object) array(
     'id' => 109,
     'test_page_id' => 4,
     'title' => 'Troponin I',
     'description' => 'Highly specific to the heart muscle. Elevated levels indicate myocardial injury.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  17 => 
  (object) array(
     'id' => 110,
     'test_page_id' => 4,
     'title' => 'Troponin T',
     'description' => 'Also specific to the heart muscle. Used similarly to cTnI to detect heart damage.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  18 => 
  (object) array(
     'id' => 111,
     'test_page_id' => 5,
     'title' => 'TSH Level',
     'description' => 'Measures the pituitary gland\'s signal to the thyroid gland. It acts as a feedback mechanism.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  19 => 
  (object) array(
     'id' => 112,
     'test_page_id' => 6,
     'title' => 'Free T4',
     'description' => 'The unbound, biologically active portion of thyroxine in the blood.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  20 => 
  (object) array(
     'id' => 113,
     'test_page_id' => 7,
     'title' => 'RBC Count',
     'description' => 'Cells that carry oxygen from your lungs to the rest of your body.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  21 => 
  (object) array(
     'id' => 114,
     'test_page_id' => 7,
     'title' => 'WBC Count',
     'description' => 'Cells that fight infection and are part of the immune system.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  22 => 
  (object) array(
     'id' => 115,
     'test_page_id' => 7,
     'title' => 'Platelets',
     'description' => 'Cell fragments that help your blood clot to stop bleeding.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  23 => 
  (object) array(
     'id' => 116,
     'test_page_id' => 7,
     'title' => 'Hemoglobin (Hb)',
     'description' => 'The oxygen-carrying protein in red blood cells.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  24 => 
  (object) array(
     'id' => 117,
     'test_page_id' => 7,
     'title' => 'Hematocrit',
     'description' => 'The proportion of red blood cells to the fluid component (plasma) in your blood.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  25 => 
  (object) array(
     'id' => 118,
     'test_page_id' => 8,
     'title' => 'Neutrophils',
     'description' => 'The most common type of white blood cell, primarily responsible for fighting bacterial infections.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  26 => 
  (object) array(
     'id' => 119,
     'test_page_id' => 8,
     'title' => 'Lymphocytes',
     'description' => 'Crucial for fighting viral infections and producing antibodies.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  27 => 
  (object) array(
     'id' => 120,
     'test_page_id' => 8,
     'title' => 'Monocytes',
     'description' => 'Help break down bacteria and cellular debris.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  28 => 
  (object) array(
     'id' => 121,
     'test_page_id' => 8,
     'title' => 'Eosinophils',
     'description' => 'Involved in allergic reactions and fighting parasitic infections.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  29 => 
  (object) array(
     'id' => 122,
     'test_page_id' => 8,
     'title' => 'Basophils',
     'description' => 'Play a role in asthma and allergic responses by releasing histamine.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  30 => 
  (object) array(
     'id' => 123,
     'test_page_id' => 9,
     'title' => 'Hemoglobin',
     'description' => 'Measures the amount of the oxygen-carrying protein in your blood, expressed in grams per deciliter (g/dL).',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  31 => 
  (object) array(
     'id' => 124,
     'test_page_id' => 9,
     'title' => 'Hematocrit',
     'description' => 'Measures the proportion of red blood cells in your blood, expressed as a percentage.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  32 => 
  (object) array(
     'id' => 125,
     'test_page_id' => 4,
     'title' => 'Significance',
     'description' => 'Provides critical insights into your overall health and helps diagnose underlying conditions.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  33 => 
  (object) array(
     'id' => 126,
     'test_page_id' => 4,
     'title' => 'Accuracy',
     'description' => 'Utilizes state-of-the-art laboratory equipment for precise and reliable results.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  34 => 
  (object) array(
     'id' => 127,
     'test_page_id' => 5,
     'title' => 'Significance',
     'description' => 'Provides critical insights into your overall health and helps diagnose underlying conditions.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  35 => 
  (object) array(
     'id' => 128,
     'test_page_id' => 5,
     'title' => 'Accuracy',
     'description' => 'Utilizes state-of-the-art laboratory equipment for precise and reliable results.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  36 => 
  (object) array(
     'id' => 129,
     'test_page_id' => 5,
     'title' => 'Monitoring',
     'description' => 'Essential for tracking the progression of diseases and the effectiveness of treatments.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  37 => 
  (object) array(
     'id' => 130,
     'test_page_id' => 6,
     'title' => 'Significance',
     'description' => 'Provides critical insights into your overall health and helps diagnose underlying conditions.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  38 => 
  (object) array(
     'id' => 131,
     'test_page_id' => 6,
     'title' => 'Accuracy',
     'description' => 'Utilizes state-of-the-art laboratory equipment for precise and reliable results.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  39 => 
  (object) array(
     'id' => 132,
     'test_page_id' => 6,
     'title' => 'Monitoring',
     'description' => 'Essential for tracking the progression of diseases and the effectiveness of treatments.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  40 => 
  (object) array(
     'id' => 133,
     'test_page_id' => 9,
     'title' => 'Significance',
     'description' => 'Provides critical insights into your overall health and helps diagnose underlying conditions.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
  41 => 
  (object) array(
     'id' => 134,
     'test_page_id' => 9,
     'title' => 'Accuracy',
     'description' => 'Utilizes state-of-the-art laboratory equipment for precise and reliable results.',
     'icon' => NULL,
     'created_at' => '2026-09-16 10:48:59',
     'updated_at' => '2026-09-16 10:48:59',
  ),
);
foreach($components as $c) { DB::table('test_page_components')->insert((array)$c); }

$results = array (
  0 => 
  (object) array(
     'id' => 59,
     'test_page_id' => 1,
     'title' => 'High or Low Glucose',
     'description' => 'May indicate diabetes, prediabetes, or hypoglycemia.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  1 => 
  (object) array(
     'id' => 60,
     'test_page_id' => 1,
     'title' => 'Abnormal Kidney Markers (BUN/Creatinine)',
     'description' => 'Could suggest kidney disease or dehydration.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  2 => 
  (object) array(
     'id' => 61,
     'test_page_id' => 1,
     'title' => 'Abnormal Liver Markers (ALT/AST/ALP)',
     'description' => 'May indicate liver damage, inflammation, or bile duct issues.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  3 => 
  (object) array(
     'id' => 62,
     'test_page_id' => 2,
     'title' => 'Abnormal Electrolytes',
     'description' => 'Can be caused by dehydration, kidney disease, or certain medications.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  4 => 
  (object) array(
     'id' => 63,
     'test_page_id' => 2,
     'title' => 'Elevated BUN or Creatinine',
     'description' => 'Often the first sign that the kidneys are not filtering waste properly.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  5 => 
  (object) array(
     'id' => 64,
     'test_page_id' => 2,
     'title' => 'Elevated Glucose',
     'description' => 'May indicate impaired glucose tolerance or diabetes.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  6 => 
  (object) array(
     'id' => 65,
     'test_page_id' => 3,
     'title' => 'High LDL',
     'description' => 'Increases your risk of heart disease and stroke.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  7 => 
  (object) array(
     'id' => 66,
     'test_page_id' => 3,
     'title' => 'Low HDL',
     'description' => 'Also increases your risk of heart disease. Higher HDL levels are protective.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  8 => 
  (object) array(
     'id' => 67,
     'test_page_id' => 3,
     'title' => 'High Triglycerides',
     'description' => 'Associated with metabolic syndrome, fatty liver disease, and increased cardiovascular risk.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  9 => 
  (object) array(
     'id' => 68,
     'test_page_id' => 4,
     'title' => 'Normal (Negative) Results',
     'description' => 'Suggests that your symptoms are not caused by a heart attack.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  10 => 
  (object) array(
     'id' => 69,
     'test_page_id' => 4,
     'title' => 'Elevated (Positive) Results',
     'description' => 'Indicates damage to the heart muscle. If the levels rise and fall over a series of tests, it is highly indicative of a heart attack.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  11 => 
  (object) array(
     'id' => 70,
     'test_page_id' => 5,
     'title' => 'High TSH',
     'description' => 'Usually indicates an underactive thyroid (hypothyroidism). The pituitary is producing more TSH to try to stimulate the thyroid.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  12 => 
  (object) array(
     'id' => 71,
     'test_page_id' => 5,
     'title' => 'Low TSH',
     'description' => 'Usually indicates an overactive thyroid (hyperthyroidism). The pituitary is making less TSH because there is already too much thyroid hormone in the blood.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  13 => 
  (object) array(
     'id' => 72,
     'test_page_id' => 6,
     'title' => 'High Free T4',
     'description' => 'Indicates hyperthyroidism (an overactive thyroid).',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  14 => 
  (object) array(
     'id' => 73,
     'test_page_id' => 6,
     'title' => 'Low Free T4',
     'description' => 'Indicates hypothyroidism (an underactive thyroid).',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  15 => 
  (object) array(
     'id' => 74,
     'test_page_id' => 7,
     'title' => 'Low RBC, Hemoglobin, or Hematocrit',
     'description' => 'Indicates anemia, which can cause fatigue and weakness.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  16 => 
  (object) array(
     'id' => 75,
     'test_page_id' => 7,
     'title' => 'High WBC Count',
     'description' => 'May indicate an infection, inflammation, or an immune system disorder.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  17 => 
  (object) array(
     'id' => 76,
     'test_page_id' => 7,
     'title' => 'Low Platelet Count',
     'description' => 'Can lead to prolonged bleeding or easy bruising.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  18 => 
  (object) array(
     'id' => 77,
     'test_page_id' => 8,
     'title' => 'High Neutrophils',
     'description' => 'Often indicates a bacterial infection or acute inflammation.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  19 => 
  (object) array(
     'id' => 78,
     'test_page_id' => 8,
     'title' => 'High Lymphocytes',
     'description' => 'Frequently seen with viral infections.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  20 => 
  (object) array(
     'id' => 79,
     'test_page_id' => 8,
     'title' => 'High Eosinophils',
     'description' => 'Can indicate an allergic reaction, asthma, or a parasitic infection.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  21 => 
  (object) array(
     'id' => 80,
     'test_page_id' => 9,
     'title' => 'Low H&H Levels',
     'description' => 'Indicates anemia, which can be caused by iron deficiency, blood loss, or chronic disease.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  22 => 
  (object) array(
     'id' => 81,
     'test_page_id' => 9,
     'title' => 'High H&H Levels',
     'description' => 'May indicate polycythemia vera, lung disease, smoking, or severe dehydration.',
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  23 => 
  (object) array(
     'id' => 82,
     'test_page_id' => 4,
     'title' => 'Normal / Reference Range',
     'description' => 'Indicates that your levels fall within the expected range for a healthy individual.',
     'created_at' => '2026-09-16 10:50:46',
     'updated_at' => '2026-09-16 10:50:46',
  ),
  24 => 
  (object) array(
     'id' => 83,
     'test_page_id' => 5,
     'title' => 'Normal / Reference Range',
     'description' => 'Indicates that your levels fall within the expected range for a healthy individual.',
     'created_at' => '2026-09-16 10:50:46',
     'updated_at' => '2026-09-16 10:50:46',
  ),
  25 => 
  (object) array(
     'id' => 84,
     'test_page_id' => 6,
     'title' => 'Normal / Reference Range',
     'description' => 'Indicates that your levels fall within the expected range for a healthy individual.',
     'created_at' => '2026-09-16 10:50:46',
     'updated_at' => '2026-09-16 10:50:46',
  ),
  26 => 
  (object) array(
     'id' => 85,
     'test_page_id' => 9,
     'title' => 'Normal / Reference Range',
     'description' => 'Indicates that your levels fall within the expected range for a healthy individual.',
     'created_at' => '2026-09-16 10:50:46',
     'updated_at' => '2026-09-16 10:50:46',
  ),
);
foreach($results as $r) { DB::table('test_page_results')->insert((array)$r); }

$faqs = array (
  0 => 
  (object) array(
     'id' => 34,
     'service_id' => 1,
     'question' => 'Why did my doctor order a BMP instead of a CMP?',
     'answer' => 'If your doctor only needs to check your kidney function, electrolytes, and blood sugar, a BMP is sufficient. A CMP is used when liver function also needs to be evaluated.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 2,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  1 => 
  (object) array(
     'id' => 35,
     'service_id' => 1,
     'question' => 'Can medications affect my BMP results?',
     'answer' => 'Yes, many medications (like diuretics or blood pressure pills) can affect electrolyte levels. Always inform your doctor about all medications you are taking.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 2,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  2 => 
  (object) array(
     'id' => 36,
     'service_id' => 1,
     'question' => 'At what age should I start getting a lipid panel?',
     'answer' => 'The American Heart Association recommends that all adults aged 20 or older have their cholesterol checked every 4 to 6 years. Those with cardiovascular disease risk factors may need more frequent testing.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 3,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  3 => 
  (object) array(
     'id' => 37,
     'service_id' => 1,
     'question' => 'How can I improve my lipid panel results?',
     'answer' => 'Lifestyle changes such as eating a heart-healthy diet, exercising regularly, losing weight, and quitting smoking can significantly improve your lipid profile.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 3,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  4 => 
  (object) array(
     'id' => 38,
     'service_id' => 2,
     'question' => 'Why are multiple troponin tests done?',
     'answer' => 'Troponin levels can take several hours to rise after a heart attack begins. Performing the test multiple times over 6 to 12 hours ensures that a delayed rise in troponin is not missed.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 9,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  5 => 
  (object) array(
     'id' => 39,
     'service_id' => 2,
     'question' => 'Can anything besides a heart attack cause high troponin?',
     'answer' => 'Yes, other conditions that strain the heart can elevate troponin, including pulmonary embolism, congestive heart failure, and severe infections.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 9,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  6 => 
  (object) array(
     'id' => 40,
     'service_id' => 2,
     'question' => 'What are the symptoms of an abnormal TSH?',
     'answer' => 'High TSH (hypothyroidism) can cause fatigue, weight gain, and feeling cold. Low TSH (hyperthyroidism) can cause anxiety, weight loss, and rapid heartbeat.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 7,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  7 => 
  (object) array(
     'id' => 41,
     'service_id' => 2,
     'question' => 'If my TSH is abnormal, what happens next?',
     'answer' => 'Your doctor will likely order additional tests, such as Free T4 and Free T3, to pinpoint the exact cause of the thyroid dysfunction.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 7,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  8 => 
  (object) array(
     'id' => 42,
     'service_id' => 2,
     'question' => 'What is the difference between Total T4 and Free T4?',
     'answer' => 'Total T4 measures both the bound and free forms of the hormone, and can be affected by the amount of protein in the blood. Free T4 measures only the active form and is considered a more accurate reflection of thyroid hormone function.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 8,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  9 => 
  (object) array(
     'id' => 43,
     'service_id' => 2,
     'question' => 'Can pregnancy affect my Free T4 levels?',
     'answer' => 'Yes, pregnancy alters blood proteins and can affect thyroid hormone levels. Specialized reference ranges are used during pregnancy.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 8,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  10 => 
  (object) array(
     'id' => 44,
     'service_id' => 3,
     'question' => 'How often should I get a CBC?',
     'answer' => 'A CBC is routinely performed during annual physical exams. It may be done more frequently if you are undergoing treatments like chemotherapy or if you have a blood disorder.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 13,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  11 => 
  (object) array(
     'id' => 45,
     'service_id' => 3,
     'question' => 'Can dehydration affect a CBC?',
     'answer' => 'Yes, severe dehydration can cause your hematocrit and red blood cell count to appear artificially high.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 13,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  12 => 
  (object) array(
     'id' => 46,
     'service_id' => 3,
     'question' => 'Why did my doctor order a CBC with differential instead of a regular CBC?',
     'answer' => 'If your doctor suspects an infection, immune disorder, or leukemia, the differential provides essential clues about the specific nature of the problem.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 14,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  13 => 
  (object) array(
     'id' => 47,
     'service_id' => 3,
     'question' => 'Are abnormal differential results always serious?',
     'answer' => 'No. Minor fluctuations can occur due to stress, exercise, or minor viral illnesses. Your doctor will interpret the results in context.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 14,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  14 => 
  (object) array(
     'id' => 48,
     'service_id' => 3,
     'question' => 'What is a normal hemoglobin level?',
     'answer' => 'Normal ranges vary by age and sex. Generally, for men it is 13.8 to 17.2 g/dL, and for women it is 12.1 to 15.1 g/dL.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 15,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
  15 => 
  (object) array(
     'id' => 49,
     'service_id' => 3,
     'question' => 'Are H&H tests part of a CBC?',
     'answer' => 'Yes, both hemoglobin and hematocrit are standard components of a Complete Blood Count (CBC). However, they can also be ordered separately (often called an H&H) for quick monitoring of anemia or blood loss.',
     'is_active' => 1,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
     'test_page_id' => NULL,
     'test_id' => 15,
     'tab_name' => NULL,
     'section_heading' => NULL,
  ),
);
foreach($faqs as $f) { DB::table('service_faqs')->insert((array)$f); }

$tests = array (
  0 => 
  (object) array(
     'id' => 2,
     'service_id' => 1,
     'name' => 'Basic Metabolic Panel',
     'heading' => 'Basic Metabolic Panel',
     'description' => 'Evaluates glucose, electrolytes, kidney function, and other essential metabolic markers.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-15 08:23:03',
     'updated_at' => '2026-09-15 08:23:03',
  ),
  1 => 
  (object) array(
     'id' => 3,
     'service_id' => 1,
     'name' => 'Lipid Panel',
     'heading' => 'Lipid Panel',
     'description' => 'Measures cholesterol and triglyceride levels to help assess cardiovascular health.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-15 08:23:03',
     'updated_at' => '2026-09-15 08:23:03',
  ),
  2 => 
  (object) array(
     'id' => 4,
     'service_id' => 1,
     'name' => 'Blood Glucose',
     'heading' => 'Blood Glucose',
     'description' => 'Measures blood sugar levels to support assessment and monitoring of glucose control.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-15 08:23:03',
     'updated_at' => '2026-09-15 08:23:03',
  ),
  3 => 
  (object) array(
     'id' => 5,
     'service_id' => 1,
     'name' => 'Liver Function Tests (LFT)',
     'heading' => 'Liver Function Tests (LFT)',
     'description' => 'Evaluates enzymes and proteins that provide information about liver function and health.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-15 08:23:03',
     'updated_at' => '2026-09-15 08:23:03',
  ),
  4 => 
  (object) array(
     'id' => 6,
     'service_id' => 1,
     'name' => 'Kidney Function Tests',
     'heading' => 'Kidney Function Tests',
     'description' => 'Measures key markers that help assess kidney function and overall renal health.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-15 08:23:03',
     'updated_at' => '2026-09-15 08:23:03',
  ),
  5 => 
  (object) array(
     'id' => 7,
     'service_id' => 2,
     'name' => 'Thyroid Stimulating Hormone (TSH)',
     'heading' => 'Thyroid function assessment',
     'description' => 'Measures TSH to help assess thyroid function and support evaluation of thyroid-related conditions.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  6 => 
  (object) array(
     'id' => 8,
     'service_id' => 2,
     'name' => 'Free T4',
     'heading' => 'Free T4 thyroid hormone test',
     'description' => 'Measures free thyroxine levels to provide additional information about thyroid function.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  7 => 
  (object) array(
     'id' => 9,
     'service_id' => 2,
     'name' => 'Troponin',
     'heading' => 'Troponin cardiac marker',
     'description' => 'Measures troponin, a key cardiac marker used to support assessment of heart muscle injury.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  8 => 
  (object) array(
     'id' => 10,
     'service_id' => 2,
     'name' => 'Vitamin D',
     'heading' => 'Vitamin D level test',
     'description' => 'Measures vitamin D levels to help assess nutritional status and support bone health evaluation.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  9 => 
  (object) array(
     'id' => 11,
     'service_id' => 2,
     'name' => 'Beta-hCG / Pregnancy Test',
     'heading' => 'Beta-hCG pregnancy test',
     'description' => 'Measures beta-hCG to support pregnancy testing and related clinical assessment.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  10 => 
  (object) array(
     'id' => 12,
     'service_id' => 2,
     'name' => 'Prostate-Specific Antigen (PSA)',
     'heading' => 'PSA screening test',
     'description' => 'Measures PSA levels to support prostate health assessment and clinical monitoring.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  11 => 
  (object) array(
     'id' => 13,
     'service_id' => 3,
     'name' => 'Complete Blood Count (CBC)',
     'heading' => 'Complete Blood Count',
     'description' => 'Provides an overview of red cells, white cells, hemoglobin, hematocrit, and platelets.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  12 => 
  (object) array(
     'id' => 14,
     'service_id' => 3,
     'name' => 'CBC with Differential',
     'heading' => 'CBC with Differential',
     'description' => 'Measures blood cell counts and the distribution of white blood cell types.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  13 => 
  (object) array(
     'id' => 15,
     'service_id' => 3,
     'name' => 'Hemoglobin & Hematocrit',
     'heading' => 'Hemoglobin & Hematocrit',
     'description' => 'Assesses oxygen-carrying capacity and the proportion of red blood cells in the blood.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  14 => 
  (object) array(
     'id' => 16,
     'service_id' => 3,
     'name' => 'Platelet Count',
     'heading' => 'Platelet Count',
     'description' => 'Measures platelets, which play an important role in normal blood clotting.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  15 => 
  (object) array(
     'id' => 17,
     'service_id' => 3,
     'name' => 'Reticulocyte Count',
     'heading' => 'Reticulocyte Count',
     'description' => 'Measures young red blood cells to support evaluation of bone marrow response.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  16 => 
  (object) array(
     'id' => 18,
     'service_id' => 3,
     'name' => 'Peripheral Blood Smear',
     'heading' => 'Peripheral Blood Smear',
     'description' => 'Examines blood cell appearance and morphology to support further hematology evaluation.',
     'image_path' => NULL,
     'is_active' => 0,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 10:40:48',
     'updated_at' => '2026-09-16 10:40:48',
  ),
  17 => 
  (object) array(
     'id' => 21,
     'service_id' => 1,
     'name' => 'Comprehensive Metabolic Panel',
     'heading' => 'Comprehensive Metabolic Panel',
     'description' => 'Measures key substances in the blood to assess metabolism, liver, kidney, and overall health.',
     'image_path' => NULL,
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 11:56:14',
     'updated_at' => '2026-09-16 11:56:14',
  ),
  18 => 
  (object) array(
     'id' => 22,
     'service_id' => 1,
     'name' => 'hg',
     'heading' => 'fd',
     'description' => 'uytr',
     'image_path' => 'tests/XU7BlZuzhysGSYfBGiPTR1OenlEbHZVU3gejacuY.jpg',
     'is_active' => 1,
     'faq_heading' => NULL,
     'faq_description' => NULL,
     'created_at' => '2026-09-16 12:10:49',
     'updated_at' => '2026-09-16 12:10:49',
  ),
);
foreach($tests as $t) { DB::table('tests')->insert((array)$t); }

echo 'Database synchronized successfully!';
