<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
class AdminTestController extends Controller {
 public function index(){ $this->guard(); return view('admin-tests',['services'=>DB::table('services')->where('is_active',true)->orderBy('name')->get(),'tests'=>DB::table('tests')->join('services','tests.service_id','=','services.id')->select('tests.*','services.name as service_name')->latest('tests.id')->get()]); }
 public function store(Request $request){$this->guard();$data=$request->validate(['service_id'=>'required|exists:services,id','name'=>'required|string|max:150','heading'=>'nullable|string|max:180','description'=>'nullable|string|max:1500','is_active'=>'required|boolean','image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']);$path=$request->hasFile('image')?$request->file('image')->store('tests','public'):null;DB::table('tests')->insert(['service_id'=>$data['service_id'],'name'=>$data['name'],'heading'=>$data['heading']??$data['name'],'description'=>$data['description']??null,'image_path'=>$path,'is_active'=>$data['is_active'],'created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Test added and assigned to the selected service.');}
 public function edit($id){$this->guard();$test=DB::table('tests')->where('id',$id)->first();abort_unless($test,404);return view('admin-test-edit',['test'=>$test,'services'=>DB::table('services')->where('is_active',true)->orderBy('name')->get()]);}
 public function update(Request $request,$id){$this->guard();$test=DB::table('tests')->where('id',$id)->first();abort_unless($test,404);$data=$request->validate(['service_id'=>'required|exists:services,id','name'=>'required|string|max:150','heading'=>'nullable|string|max:180','description'=>'nullable|string|max:1500','is_active'=>'required|boolean','image'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']);$values=['service_id'=>$data['service_id'],'name'=>$data['name'],'heading'=>$data['heading']??$data['name'],'description'=>$data['description']??null,'is_active'=>$data['is_active'],'updated_at'=>now()];if($request->hasFile('image'))$values['image_path']=$request->file('image')->store('tests','public');DB::table('tests')->where('id',$test->id)->update($values);return redirect()->route('admin.tests.index')->with('success','Test updated successfully.');}
 public function destroy($id){$this->guard();DB::table('tests')->where('id',$id)->delete();return back()->with('success','Test deleted successfully.');}
 private function guard(){abort_unless(Auth::check()&&Auth::user()->is_admin,403);}
}
